Billing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.record_list.as_view(), name='record_list'),
    path('record/detail/<pk>', views.record_detail.as_view(), name='record_detail'),
    path('record/update/<pk>', views.record_update.as_view(), name='record_update'),
    path('record/delete/<pk>', views.record_delete.as_view(), name='record_delete'),
    path('record/create/', views.record_create.as_view(), name='record_create'),
    path('account/', views.account_list.as_view(), name='account_list'),
    path('account/create/', views.account_create.as_view(), name='account_create'),
    path('account/update/<pk>', views.account_update.as_view(), name='account_update'),
    path('account/delete/<pk>', views.account_delete.as_view(), name='account_delete'),
]

Billing_Web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import js_catalog_template

urlpatterns = [
    path('billing/', include('Billing.urls')),
    path('admin/', admin.site.urls),

]

Billing/models.py
import uuid
from django.db import models
from django.utils.timezone import now


# Create your models here.

class Record(models.Model):
    EXPEND = 'EX'
    INCOME = 'IN'
    TRANSFER = 'TR'
    MODE_CHOICES = ((EXPEND, '支出'), (INCOME, '收入'), (TRANSFER, '轉帳'))
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='UUID')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='建立時間')
    transaction_date = models.DateField(default=now, verbose_name='交易時間')
    own_account = models.ForeignKey('Account', on_delete=models.CASCADE, verbose_name='帳戶')
    record_type = models.CharField(max_length=2, choices=MODE_CHOICES, null=False, default=EXPEND, verbose_name='記錄型態')
    amount = models.DecimalField(max_digits=11, decimal_places=2, null=False, default=0, verbose_name='金額')
    description = models.TextField(blank=True, verbose_name='備註')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.record_type == self.INCOME:
            self.own_account.balance += self.amount
        else:
            self.own_account.balance -= self.amount
        self.own_account.save()
        super().save(force_insert, force_update, using, update_fields)

    def delete(self, using=None, keep_parents=False):
        if self.record_type == self.INCOME:
            self.own_account.balance -= self.amount
        else:
            self.own_account.balance += self.amount
        self.own_account.save()
        super().delete(using=None, keep_parents=False)


class Account(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name='UUID')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='建立時間')
    name = models.CharField(max_length=50, verbose_name='帳戶名稱')
    initial_amount = models.DecimalField(max_digits=11, decimal_places=2, null=False, default=0, verbose_name='初始金額')
    balance = models.DecimalField(max_digits=11, decimal_places=2, null=False, default=0, verbose_name='餘額')
    description = models.TextField(blank=True, verbose_name='備註')

    def __str__(self):
        return self.name

Billing/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from . import models


class Record_Form(forms.ModelForm):
    class Meta:
        model = models.Record
        fields = '__all__'
        widgets = {
            'transaction_date': AdminDateWidget()
        }


class Account_Form(forms.ModelForm):
    class Meta:
        model = models.Account
        exclude = ['balance']

Billing/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView

from . import models, forms


# Create your views here.

class record_list(ListView):
    model = models.Record
    ordering = 'transaction_date'
    template_name = 'record_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['record_form'] = forms.Record_Form()
        context['total_expend'] = sum(
            [each.amount for each in self.model.objects.filter(record_type=models.Record.EXPEND)])
        context['total_income'] = sum(
            [each.amount for each in self.model.objects.filter(record_type=models.Record.INCOME)])
        context['balance'] = context['total_income'] - context['total_expend']
        return context


class record_create(CreateView):
    form_class = forms.Record_Form
    template_name = 'record_form.html'

    def get_success_url(self):
        messages.success(self.request, '建立成功')
        return reverse('record_list')


class record_update(UpdateView):
    model = models.Record
    form_class = forms.Record_Form
    template_name = 'record_form.html'

    def get_success_url(self):
        messages.success(self.request, '更新成功')
        return reverse('record_list')


class record_detail(DetailView):
    model = models.Record
    template_name = 'record_detail.html'


class record_delete(DeleteView):
    model = models.Record
    template_name = 'delete_conform.html'

    def get_success_url(self):
        messages.success(self.request, '刪除成功')
        return reverse('record_list')


class account_list(ListView):
    model = models.Account
    template_name = 'account_list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account_form'] = forms.Account_Form()
        return context


class account_create(CreateView):
    form_class = forms.Account_Form
    template_name = 'account_form.html'

    def form_valid(self, form):
        form.instance.balance = form.instance.initial_amount
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '建立成功')
        return reverse('account_list')


class account_update(UpdateView):
    model = models.Account
    form_class = forms.Account_Form
    template_name = 'account_form.html'

    def form_valid(self, form):
        oid_initial_amount = self.get_object().balance
        form.instance.balance += form.instance.initial_amount - oid_initial_amount
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, '更新成功')
        return reverse('account_list')


class account_detail(DetailView):
    model = models.Account


class account_delete(DeleteView):
    model = models.Account
    template_name = 'delete_conform.html'

    def get_success_url(self):
        messages.success(self.request, '刪除成功')
        return reverse('account_list')

Billing/templates/_base.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

<!DOCTYPE html>
<html>
<head>
    <title>記一下帳</title>
    {% block head %}
    {% endblock %}
</head>
<body>

{% block navbar %}
    {% include '_navbar.html' %}
{% endblock %}

<div class="container-fluid">
    <div class="text-center">
        {% bootstrap_messages %}
    </div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

Billing/templates/_navbar.html
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=0 %}

<nav class="navbar navbar-static-top navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'record_list' %}">Billing</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'account_list' %}">帳戶管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

Billing/templates/account_form.html
{% extends '_base.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">送出</button>
    </form>
{% endblock %}

Billing/templates/account_list.html
{% extends '_base.html' %}
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block content %}
    {% fontawesome_stylesheet %}
    <div class="row">
        <div class="col-md-2 text-center">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">新增帳戶</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="/billing/account/create/">
                        {% csrf_token %}
                        {% bootstrap_form account_form %}
                        <button type="submit" class="btn btn-primary">新增</button>
                    </form>
                </div>
            </div>

        </div>
        <div class="col-md-10 text-center">
            <table class="table table-hover table-condensed ">
                <thead>
                <th>帳戶名稱</th>
                <th>初始金額</th>
                <th>餘額</th>
                <th>操作</th>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object }}</td>
                        <td>{{ object.initial_amount }}</td>
                        <td>{{ object.balance }}</td>
                        <td>
                            <a href="#">
                                <button type="button" class="btn btn-default">{% fontawesome_icon 'eye' %}</button>
                            </a>
                            <a href="{% url 'account_update' object.uuid %}">
                                <button type="button" class="btn btn-primary">{% fontawesome_icon 'edit' %}</button>
                            </a>
                            <a href="{% url 'account_delete' object.uuid %}">
                                <button type="button" class="btn btn-danger">{% fontawesome_icon 'trash-o' %}</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

Billing/templates/delete_conform.html
{% extends '_base.html' %}
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
            <form method="post">
                {% csrf_token %}
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h3 class="panel-title">確定要刪除?</h3>
                    </div>
                    <div class="panel-body">
                        <button type="submit" class="btn btn-default">確定</button>
                    </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

Billing/templates/record_delete.html
{% extends '_base.html' %}
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4 text-center">
            <form method="post">
                {% csrf_token %}
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h3 class="panel-title">確定要刪除?</h3>
                    </div>
                    <div class="panel-body">
                        <button type="submit" class="btn btn-default">確定</button>
                    </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

Billing/templates/record_detail.html
{% extends '_base.html' %}
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}


{% block content %}
    {% fontawesome_stylesheet %}
    <table class="table table-striped">
        <thead>
        <th>項目</th>
        <th>資料</th>
        </thead>
        <tbody>
        <tr>
            <td class="success">帳戶</td>
            <td>{{ object.own_account }}</td>
        </tr>
        <tr>
            <td class="success">記錄類型</td>
            <td>{{ object.get_record_type_display }}</td>
        </tr>
        <tr>
            <td class="success">交易日期</td>
            <td>{{ object.transaction_date }}</td>
        </tr>
        <tr>
            <td class="success">金額</td>
            <td>{{ object.amount }}</td>
        </tr>
        <tr>
            <td class="success">備註</td>
            <td>{{ object.description }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

Billing/templates/record_form.html
{% extends '_base.html' %}
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary">送出</button>
    </form>
{% endblock %}

Billing/templates/record_list.html
{% extends '_base.html' %}
{% load fontawesome %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1 %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
{% endblock %}

{% block content %}
    {% fontawesome_stylesheet %}
    <div class="row">
        <div class="col-md-2 text-center">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">總報表</h3>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                        <th></th>
                        <th>金額</th>
                        </thead>
                        <tbody>
                        <tr>
                            <td>總支出</td>
                            <td>{{ total_expend }}</td>
                        </tr>
                        <tr>
                            <td>總收入</td>
                            <td>{{ total_income }}</td>
                        </tr>
                        <tr>
                            <td>剩下資產</td>
                            <td>{{ balance }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">建立記錄</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="/billing/record/create/">
                        {% csrf_token %}
                        {% bootstrap_form record_form %}
                        <button type="submit" class="btn btn-primary">新增</button>
                    </form>
                </div>
            </div>

        </div>
        <div class="col-md-10 text-center">
            <table class="table table-hover table-condensed ">
                <thead>
                <th>記錄類型</th>
                <th>交易日期</th>
                <th>金額</th>
                <th>操作</th>
                </thead>
                <tbody>
                {% for object in object_list %}
                    {% if object.record_type == object.EXPEND %}
                        <tr class="active">
                            {% elif object.record_type == object.INCOME %}
                        <tr class="warning">
                            {% else %}
                        <tr class="info">
                    {% endif %}

                <td>{{ object.get_record_type_display }}</td>
                <td>{{ object.transaction_date }}</td>
                <td>{{ object.amount }}</td>
                <td>
                    <a href="{% url 'record_detail' object.pk %}">
                        <button type="button" class="btn btn-default">{% fontawesome_icon 'eye' %}</button>
                    </a>
                    <a href="{% url 'record_update' object.pk %}">
                        <button type="button" class="btn btn-primary">{% fontawesome_icon 'edit' %}</button>
                    </a>
                    <a href="{% url 'record_delete' object.pk %}">
                        <button type="button" class="btn btn-danger">{% fontawesome_icon 'trash-o' %}</button>
                    </a>
                </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}